@for ($i = 0; $i <= 9 ; $i++)
  <div class="vertical vertical{{ $i }}">
    <div class="horizontal horizontal000" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal001" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal002" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal003" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal004" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal005" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal006" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal007" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal008" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
    <div class="horizontal horizontal010" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal011" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal012" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal013" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal014" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal015" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal016" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal017" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal018" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
    <div class="horizontal horizontal020" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal021" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal022" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal023" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal024" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal025" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal026" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal027" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal028" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
    <div class="horizontal horizontal030" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal031" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal032" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal033" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal034" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal035" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal036" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal037" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal038" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
    <div class="horizontal horizontal040" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal041" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal042" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal043" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal044" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal045" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal046" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal047" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal048" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
    <div class="horizontal horizontal050" style="background: url( {{ asset('bg_img/1.jpg') }} );"></div>
    <div class="horizontal horizontal051" style="background: url( {{ asset('bg_img/2.jpg') }} );"></div>
    <div class="horizontal horizontal052" style="background: url( {{ asset('bg_img/3.jpg') }} );"></div>
    <div class="horizontal horizontal053" style="background: url( {{ asset('bg_img/4.jpg') }} );"></div>
    <div class="horizontal horizontal054" style="background: url( {{ asset('bg_img/5.jpg') }} );"></div>
    <div class="horizontal horizontal055" style="background: url( {{ asset('bg_img/6.jpg') }} );"></div>
    <div class="horizontal horizontal056" style="background: url( {{ asset('bg_img/7.jpg') }} );"></div>
    <div class="horizontal horizontal057" style="background: url( {{ asset('bg_img/8.jpg') }} );"></div>
    <div class="horizontal horizontal058" style="background: url( {{ asset('bg_img/9.jpg') }} );"></div>
  </div>
@endfor
